# Generated by Django 4.0.3 on 2022-03-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntingdogsapi', '0002_alter_dog_kennel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(to='huntingdogsapi.dog'),
        ),
    ]
