# Generated by Django 4.0.3 on 2022-03-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntingdogsapi', '0003_profile_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
